(library
 (name hw2_patchwork_logic)
 (wrapped false)
 (modules hw2_patchwork_logic)
 (libraries core js_of_ocaml yojson)
 (preprocess (pps ppx_jane ppx_deriving_yojson js_of_ocaml-ppx)))

 (library
  (name hw4_patchwork_ai_heuristics)
  (wrapped false)
  (modules hw4_patchwork_ai_heuristics)
  (libraries core hw2_patchwork_logic js_of_ocaml)
  (preprocess (pps js_of_ocaml-ppx ppx_jane)))

  (library
  (name patchwork_logic_library)
  (wrapped false)
  (modules patchwork_logic_library)
  (libraries core hw2_patchwork_logic hw4_patchwork_ai_heuristics)
  (preprocess (pps ppx_jane)))
